# Find LibDRMAA
#
# LIBDRMAA_FOUND
# LIBDRMAA_LIBRARIES - DRMAA library

IF(LIBDRMAA_LIBRARIES)
  # already found
  SET(LIBDRMAA_FOUND TRUE)
ELSE()
  find_library(LIBDRMAA_LIBRARIES drmaa)
  if(NOT LIBDRMAA_LIBRARIES)
    file( GLOB LIBDRMAA_LIBRARIES /usr/lib/libdrmaa.so.?.? )
  endif()
  IF(LIBDRMAA_LIBRARIES)
    set(LIBDRMAA_LIBRARIES ${LIBDRMAA_LIBRARIES} CACHE PATH "LibDRMAA libraries" FORCE)
    SET(LIBDRMAA_FOUND TRUE)
  ELSE()
    SET(LIBDRMAA_FOUND FALSE)

    IF( LIBDRMAA_FIND_REQUIRED )
        MESSAGE( SEND_ERROR "LibDRMAA was not found." )
    ENDIF()
    IF(NOT LIBDRMAA_FIND_QUIETLY)
        MESSAGE(STATUS "LibDRMAA was not found.")
    ENDIF()
  ENDIF()

ENDIF()

