#!/bin/sh -e

# clean build directory
rm -rf ./build
mkdir ./build

# clone the repo into a dir called build/html
git clone --branch gh-pages --no-checkout git@github.com:neurospin/soma-workflow.git ./build/html

# create sphinx documentation in clear directory
make html

# add configaration file to enable _<dir>
cd ./build/html/
touch .nojekyll

# commit changes
git add .
git commit -a -m "Automatic update of soma-workflow documentation"

# send commit to github server
git push origin gh-pages

echo "You can now visit the soma-workflow page at http://neurospin.github.io/soma-workflow/" 
